CREATE TABLESPACE ts_ecard DATAFILE 
  '/udata/hisdata/hisdb/ts_ecard.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;


CREATE USER ecard IDENTIFIED BY kingstar
 DEFAULT TABLESPACE "TS_ECARD"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "TS_ECARD";

GRANT "DBA" TO ecard;
ALTER USER ecard DEFAULT ROLE "DBA";

CREATE TABLESPACE ts_his_01 DATAFILE 
  '/udata/hisdata/hisdb/ts_his01.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_02 DATAFILE 
  '/udata/hisdata/hisdb/ts_his02.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_03 DATAFILE 
  '/udata/hisdata/hisdb/ts_his03.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_04 DATAFILE 
  '/udata/hisdata/hisdb/ts_his04.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_05 DATAFILE 
  '/udata/hisdata/hisdb/ts_his05.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_06 DATAFILE 
  '/udata/hisdata/hisdb/ts_his06.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_07 DATAFILE 
  '/udata/hisdata/hisdb/ts_his07.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_08 DATAFILE 
  '/udata/hisdata/hisdb/ts_his08.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_09 DATAFILE 
  '/udata/hisdata/hisdb/ts_his09.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_10 DATAFILE 
  '/udata/hisdata/hisdb/ts_his10.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_11 DATAFILE 
  '/udata/hisdata/hisdb/ts_his11.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_12 DATAFILE 
  '/udata/hisdata/hisdb/ts_his12.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

CREATE TABLESPACE ts_his_13 DATAFILE 
  '/udata/hisdata/hisdb/ts_his13.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;

