
CREATE TABLE URP_CUSTOMER
 (STUEMP_NO    VARCHAR(30)     NOT NULL,
  STUEMP_NAME  VARCHAR(120),
  SEX          VARCHAR(1),
  CUT_TYPE     VARCHAR(60),
  DEPT_CODE    VARCHAR(10),
  DEPT_NAME    VARCHAR(120),
  S_CODE       VARCHAR(20),
  S_NAME       VARCHAR(90),
  GARDE        VARCHAR(10),
  CLASS_NO     VARCHAR(10),
  IN_DATE      DATE,
  OUT_DATE     DATE,
  IS_INSCHOOL  INTEGER,
  STATUS       VARCHAR(10),
  NATION       VARCHAR(2),
  ID_TYPE      INTEGER,
  ID_TYPENAME  VARCHAR(30),
  ID_NO        VARCHAR(30),
  TEL          VARCHAR(60),
  MOBILE       VARCHAR(80),
  EMAIL        VARCHAR(60),
  AREA         VARCHAR(2),
  AREA_NAME    VARCHAR(30),
  ADDRESS      VARCHAR(150),
  BUILDING_NO  VARCHAR(10),
  FLOOR_NO     VARCHAR(10),
  ROOM_NO      VARCHAR(10),
  MED_FEETYPE  VARCHAR(5),
  FEE_TYPE     VARCHAR(5),
  UPD_DATE     DATE,
  UPD_TIME     TIMESTAMP,
  UPD_STATUS   VARCHAR(1)    NOT NULL,
  RESERVE_1    VARCHAR(10),
  RESERVE_2    VARCHAR(10),
  RESERVE_3    VARCHAR(10),
  RESERVE_4    VARCHAR(10),
  PRIMARY KEY (STUEMP_NO)
 );


COMMENT ON TABLE URP_CUSTOMER
  IS 'URP客户信息表';

COMMENT ON COLUMN URP_CUSTOMER.STUEMP_NO IS '学/工号';
COMMENT ON COLUMN URP_CUSTOMER.STUEMP_NAME IS '姓名';
COMMENT ON COLUMN URP_CUSTOMER.SEX IS '性别';
COMMENT ON COLUMN URP_CUSTOMER.CUT_TYPE IS '人员类别名称';
COMMENT ON COLUMN URP_CUSTOMER.DEPT_CODE IS '单位代码';
COMMENT ON COLUMN URP_CUSTOMER.DEPT_NAME IS '单位名称';
COMMENT ON COLUMN URP_CUSTOMER.S_CODE IS '专业代码';
COMMENT ON COLUMN URP_CUSTOMER.S_NAME IS '专业名称';
COMMENT ON COLUMN URP_CUSTOMER.GARDE IS '年级';
COMMENT ON COLUMN URP_CUSTOMER.CLASS_NO IS '班级';
COMMENT ON COLUMN URP_CUSTOMER.IN_DATE IS '入校时间';
COMMENT ON COLUMN URP_CUSTOMER.OUT_DATE IS '预计离校时间';
COMMENT ON COLUMN URP_CUSTOMER.IS_INSCHOOL IS '在校状态';
COMMENT ON COLUMN URP_CUSTOMER.STATUS IS '状态';
COMMENT ON COLUMN URP_CUSTOMER.NATION IS '民族代码';
COMMENT ON COLUMN URP_CUSTOMER.ID_TYPE IS '证件类型';
COMMENT ON COLUMN URP_CUSTOMER.ID_TYPENAME IS '证件类别名称';
COMMENT ON COLUMN URP_CUSTOMER.ID_NO IS '证件号码';
COMMENT ON COLUMN URP_CUSTOMER.TEL IS '电话';
COMMENT ON COLUMN URP_CUSTOMER.MOBILE IS '手机';
COMMENT ON COLUMN URP_CUSTOMER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN URP_CUSTOMER.AREA IS '校区代码';
COMMENT ON COLUMN URP_CUSTOMER.AREA_NAME IS '校区名称';
COMMENT ON COLUMN URP_CUSTOMER.ADDRESS IS '地址';
COMMENT ON COLUMN URP_CUSTOMER.BUILDING_NO IS '所在宿舍楼号';
COMMENT ON COLUMN URP_CUSTOMER.FLOOR_NO IS '所在楼层号';
COMMENT ON COLUMN URP_CUSTOMER.ROOM_NO IS '所在房间号';
COMMENT ON COLUMN URP_CUSTOMER.MED_FEETYPE IS '医院收费类别';
COMMENT ON COLUMN URP_CUSTOMER.FEE_TYPE IS '收费类别';
COMMENT ON COLUMN URP_CUSTOMER.UPD_DATE IS '更新日期';
COMMENT ON COLUMN URP_CUSTOMER.UPD_TIME IS '更新时间';
COMMENT ON COLUMN URP_CUSTOMER.UPD_STATUS IS '更新状态';
COMMENT ON COLUMN URP_CUSTOMER.RESERVE_1 IS '保留字段1';
COMMENT ON COLUMN URP_CUSTOMER.RESERVE_2 IS '保留字段2';
COMMENT ON COLUMN URP_CUSTOMER.RESERVE_3 IS '保留字段3';
COMMENT ON COLUMN URP_CUSTOMER.RESERVE_4 IS '保留字段4';

create snapshot log on URP_CUSTOMER;