CREATE TABLESPACE ts_photo DATAFILE 
  '/udata/photo/photodb/ts_photo01.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED,
  '/udata/photo/photodb/ts_photo02.dbf' SIZE 1024M REUSE AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  NEXT        1024M
                  MAXEXTENTS  UNLIMITED
                )
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;


CREATE USER ecard IDENTIFIED BY kingstar
 DEFAULT TABLESPACE "TS_PHOTO"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "TS_PHOTO";

GRANT "DBA" TO ecard;
ALTER USER ecard DEFAULT ROLE "DBA";

